const WHITE: string = '#FFFFFF';
const BLACK: string = '#000000';
const MAINCOLOR: string = '#22a45d';
const GRAY: string = '#696968';
const GRAY_LIGHT: string = '#f4f4f4';
const RATING_GOLD: string = '#F3B40D';

const INPUT_COLOR = '#fbfbfb';
const INPUT_BORDER_COLOR = '#f3f2f2';
const PLACEHOLDER = '#868686';
const HEADER_TEXT = '#010f07';
const FACEBOOK_COLOR = '#395998';
const GOOGLE_COLOR = '#4285f4';
const APPLE_COLOR = '#000000';
const SECTION_TITLE = '#404751';
const PRODUCT_SEPERATOR = '#dedddd';
const SEARCH_BG = '#7676801f';
const SEARCH_TEXT = '#3c3c4399';
const SETTINGS_LIST_ITEM_LEFT = '#757c78';
const CART_ITEM_BORDER = '#6767671a';
const COUNTER_ICON_BG = '#f8f8f8';
const FILTER_CHIP_BG = '#f1f1f1';
const CART_DIALOG_ICON_BG = '#ffa829';
const CHECKBOX = '#5faf50';

const TABBAR_INACTIVE_COLOR = '#48638080';
const TABBAR_ACTIVE_COLOR = '#486380';
const MOCK_BG_YELLOW = '#f0b83b';
const MOCK_BG_RED = '#EF5B57';
const MOCK_BG_ORANGE = '#F49249';
const MOCK_BG_GRAY = '#5F5F5F';
const MOCK_BG_CYAN = '#66C4C3';

const Colors = {
  CART_DIALOG_ICON_BG,
  WHITE,
  BLACK,
  MAINCOLOR,
  CART_ITEM_BORDER,
  GRAY,
  GRAY_LIGHT,
  INPUT_COLOR,
  INPUT_BORDER_COLOR,
  SETTINGS_LIST_ITEM_LEFT,
  CHECKBOX,
  PLACEHOLDER,
  FACEBOOK_COLOR,
  PRODUCT_SEPERATOR,
  SEARCH_BG,
  SEARCH_TEXT,
  APPLE_COLOR,
  GOOGLE_COLOR,
  TABBAR_ACTIVE_COLOR,
  TABBAR_INACTIVE_COLOR,
  RATING_GOLD,
  MOCK_BG_YELLOW,
  MOCK_BG_RED,
  MOCK_BG_ORANGE,
  MOCK_BG_GRAY,
  MOCK_BG_CYAN,
  HEADER_TEXT,
  SECTION_TITLE,
  COUNTER_ICON_BG,
  FILTER_CHIP_BG,
};

export default Colors;
